/// Dev-only: build the `car_popularity` snapshot from data.gov.my.
///
///     dart run tool/build_car_popularity.dart [--years 2025,2026] [--out supabase/seed/car_popularity.sql]
///
/// Downloads each year's JPJ "Car Registration Transactions" CSV (cached under
/// `build/data_gov_my/`), streams it line by line, keeps the rolling 12 months
/// ending at the latest month in the data, and writes a single SQL upsert.
/// Paste that file into the Supabase SQL editor to publish/refresh the
/// Market insights screen — no app release needed.
///
/// The app never calls data.gov.my; only this script does.
library;

import 'dart:convert';
import 'dart:io';

import 'car_popularity_aggregator.dart';

const String _baseUrl = 'https://storage.data.gov.my/transportation';
const String _catalogueUrl =
    'https://data.gov.my/data-catalogue/registration_transactions_car';
const String _cacheDir = 'build/data_gov_my';
const String _defaultOut = 'supabase/seed/car_popularity.sql';

Future<void> main(List<String> args) async {
  final now = DateTime.now().toUtc();
  var years = [now.year - 1, now.year];
  var out = _defaultOut;
  for (var i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--years':
        years = args[++i].split(',').map((y) => int.parse(y.trim())).toList();
      case '--out':
        out = args[++i];
      case '--help' || '-h':
        stdout.writeln(
          'Usage: dart run tool/build_car_popularity.dart '
          '[--years 2025,2026] [--out $_defaultOut]',
        );
        return;
      default:
        stderr.writeln('Unknown argument: ${args[i]}');
        exitCode = 64;
        return;
    }
  }

  final aggregator = CarPopularityAggregator();
  var rows = 0;
  for (final year in years) {
    final file = await _download(year);
    if (file == null) continue;
    stdout.writeln('Reading ${file.path} …');
    var first = true;
    await for (final line
        in file
            .openRead()
            .transform(utf8.decoder)
            .transform(const LineSplitter())) {
      if (line.trim().isEmpty) continue;
      if (first) {
        // Each yearly file carries its own header; only the first one seeds
        // the column map.
        first = false;
        if (rows > 0) continue;
      }
      aggregator.add(parseCsvLine(line));
      rows++;
    }
  }
  if (rows == 0) {
    stderr.writeln('No rows read — check the years or your connection.');
    exitCode = 1;
    return;
  }

  final snapshot = aggregator.build(generatedAt: now, sourceUrl: _catalogueUrl);
  final json = jsonEncode(snapshot.toJson());

  final sql = StringBuffer()
    ..writeln(
      '-- Generated by tool/build_car_popularity.dart on '
      '${now.toIso8601String()}.',
    )
    ..writeln('-- Source: JPJ car registrations via data.gov.my (CC BY 4.0)')
    ..writeln('--   $_catalogueUrl')
    ..writeln(
      '-- Window: ${snapshot.periodLabel} '
      '(${snapshot.totalRegistrations} registrations from $rows rows; '
      '${aggregator.skipped} skipped).',
    )
    ..writeln('-- Paste into the Supabase SQL editor to publish or refresh.')
    ..writeln()
    ..writeln('insert into public.car_popularity')
    ..writeln(
      '  (id, period_label, generated_at, source_url, '
      'total_registrations, data)',
    )
    ..writeln('values (')
    ..writeln("  'latest',")
    ..writeln("  ${_quote(snapshot.periodLabel)},")
    ..writeln("  '${now.toIso8601String()}'::timestamptz,")
    ..writeln("  ${_quote(_catalogueUrl)},")
    ..writeln('  ${snapshot.totalRegistrations},')
    ..writeln('  \$car_popularity\$$json\$car_popularity\$::jsonb')
    ..writeln(')')
    ..writeln('on conflict (id) do update set')
    ..writeln('  period_label        = excluded.period_label,')
    ..writeln('  generated_at        = excluded.generated_at,')
    ..writeln('  source_url          = excluded.source_url,')
    ..writeln('  total_registrations = excluded.total_registrations,')
    ..writeln('  data                = excluded.data;');

  final outFile = File(out);
  await outFile.parent.create(recursive: true);
  await outFile.writeAsString(sql.toString());

  stdout
    ..writeln('Window: ${snapshot.periodLabel}')
    ..writeln(
      'Registrations: ${snapshot.totalRegistrations} '
      '(rows read: $rows, skipped: ${aggregator.skipped})',
    )
    ..writeln(
      'Top makers: '
      '${snapshot.topMakers.take(5).map((m) => '${m.name} ${m.count}').join(', ')}',
    )
    ..writeln('States with data: ${snapshot.byState.length}')
    ..writeln('Wrote ${outFile.path} (${sql.length} bytes)');
}

/// Fetch `cars_<year>.csv` into the cache directory unless already present.
/// Returns null (with a warning) when the year does not exist upstream.
Future<File?> _download(int year) async {
  final file = File('$_cacheDir/cars_$year.csv');
  if (await file.exists() && await file.length() > 0) {
    stdout.writeln('Using cached ${file.path}');
    return file;
  }
  final url = Uri.parse('$_baseUrl/cars_$year.csv');
  stdout.writeln('Downloading $url …');
  final client = HttpClient();
  try {
    final request = await client.getUrl(url);
    final response = await request.close();
    if (response.statusCode == HttpStatus.notFound) {
      stderr.writeln('  not found upstream — skipping $year');
      return null;
    }
    if (response.statusCode != HttpStatus.ok) {
      throw HttpException('HTTP ${response.statusCode} for $url');
    }
    await file.parent.create(recursive: true);
    final tmp = File('${file.path}.part');
    final sink = tmp.openWrite();
    var bytes = 0;
    await for (final chunk in response) {
      sink.add(chunk);
      bytes += chunk.length;
    }
    await sink.close();
    await tmp.rename(file.path);
    stdout.writeln('  saved ${(bytes / 1024 / 1024).toStringAsFixed(1)} MB');
    return file;
  } finally {
    client.close();
  }
}

String _quote(String s) => "'${s.replaceAll("'", "''")}'";
